// Syncs package.json version into src/version.ts (generated, committed) and
// the landing page wordmark badge. Run automatically via prebuild/pretest
// hooks; CI fails on drift via tests/settings-view.test.mjs.
import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const version = pkg.version;
if (typeof version !== "string" || !version) throw new Error("package.json has no version");
const out = `// Generated by scripts/sync-version.mjs — do not edit by hand.\n// Source of truth: package.json version.\nexport const ANNOTE_VERSION = ${JSON.stringify(version)};\n`;
writeFileSync(new URL("../src/version.ts", import.meta.url), out);
const indexUrl = new URL("../index.html", import.meta.url);
const index = readFileSync(indexUrl, "utf8");
const badgePattern = /<span class="wordmark-version" data-version>v[\d.]+<\/span>/;
if (!badgePattern.test(index)) throw new Error("index.html wordmark version badge missing");
const stamped = index.replace(
  /(<span class="wordmark-version" data-version>v)[\d.]+(<\/span>)/,
  `$1${version}$2`,
);
if (stamped !== index) writeFileSync(indexUrl, stamped);
console.log(`version synced: ${version}`);
