// Syncs package.json version into src/version.ts (generated, committed).
// Run automatically via prebuild/pretest hooks; CI fails on drift via
// tests/settings-view.test.mjs.
import { readFileSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const version = pkg.version;
if (typeof version !== "string" || !version) throw new Error("package.json has no version");
const out = `// Generated by scripts/sync-version.mjs — do not edit by hand.\n// Source of truth: package.json version.\nexport const ANNOTE_VERSION = ${JSON.stringify(version)};\n`;
writeFileSync(new URL("../src/version.ts", import.meta.url), out);
console.log(`version synced: ${version}`);
